SELECT 
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_STATUS,
    MONTH,
    DAY,
    YEAR,
    CASE 
        WHEN HOUR >= 5 AND HOUR < 10 THEN 'MORNING'
        WHEN HOUR >= 10 AND HOUR < 17 THEN 'AFTERNOON'
        WHEN HOUR >= 17 AND HOUR < 21 THEN 'EVENING'
        ELSE 'NIGHT'
    END AS TIME_OF_ORDER,
    ACTUAL_TURN_AROUND_TIME,
    ACTUAL_TURN_AROUND_TIME - ESTIMATED_TURN_AROUND_TIME AS DELAY_IN_DAYS,
    CASE
        WHEN ACTUAL_TURN_AROUND_TIME > ESTIMATED_TURN_AROUND_TIME
            THEN TRUE
        ELSE FALSE
    END AS IS_DELAYED,
    TIME_TO_DELIVER,
    REVIEW_SCORE

FROM {{ source('silver', 'ORDERS') }}