version: 2

sources:

  - name: bronze

    database: OLIST
    schema: BRONZE

    tables:
      - name: SELLERS
      - name: CHURN
      - name: PAYMENTS

  - name: silver

    database: OLIST
    schema: SILVER

    tables:
      - name: CUSTOMERS
      - name: ORDERS
        config:
          freshness:
            warn_after:
              count: 1
              period: day
      - name: ORDER_ITEMS
